### ISSUE TITLE
Missing Back Button

### ISSUE THREAD

**Issue by moriswala** [blackmann/locationpicker#9]
Please add back button in the AppBar. Its very useful in case of iPhone specially if user want to cancel it without selection. Thank you

**Comment by blackmann** [comment]
@moriswala alright. Will resolve it.

**Comment by dariotrombello** [comment]
Any progress on this?
My app is also crashing when just clicking on the normal android back button on the bottom.

EDIT: I resolved the crash by just implementing a simple if condition

**Comment by blackmann** [comment]
@moriswala I tried to resolve this issue by adding the back button as requested. But from design perspective, the back icon will then be close to the search icon, which will make it a bit ugly.

I suppose, iPhone users are familiar with the back gesture and can rather use that- unless convinced otherwise.

**Comment by AxeemHaider** [comment]
@blackmann Might not on Android but it should be on iPhone.

**Comment by tjjv** [comment]
This is first time I heard there is such gesture. But I am not an iPhone user, only a developer creating cross-platform app.

The back gesture seems to work, but requiring it it does not match application design guidelines or requirements. So this location picker is not usable in this app.

EDIT: Also my client who has been iPhone user for 3+ years did not know that gesture.
